# Modeling Configuration
modeling:
  methods: [gbm_l2]
  normalize: False
  log_transform: False
  robust: False
  num_jobs: 8
  random_state: 42
  log_level: INFO

  # Model-specific Configuration
  # To learn more about the configuration parameters, 
  # visit the scikit-learn or LightGBM documentation.
  rf:
    n_estimators: 50
    max_depth: 31
    criterion: "squared_error" # or "absolute_error"
  gbm:
    # naming convention gbm_[loss] or gbm_[loss]_[alpha]
    n_estimators: 100
    max_depth: 31
    num_leaves: 1000
    min_child_samples: 5
  mlp:
    # naming convention is mlp_[# layers]_[# neurons per layer]
    early_stopping: True
    max_iter: 1000000
    alpha: 0.0001
  elastic:
    alpha: 0.1
    l1_ratio: 0.5
  huber:
    max_iter: 50
